workflows:
  ios_capacitor_appstore:
    name: iOS • Capacitor → App Store (Auto signing + B64 key)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials     # Must contain: APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID, CERTIFICATE_PRIVATE_KEY_B64 (or CERTIFICATE_PRIVATE_KEY), APPLE_TEAM_ID
      vars:
        BUNDLE_ID: "com.balu.aegispulse"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: 15

    scripts:
      - name: Tool versions
        script: |
          set -e
          xcodebuild -version
          node -v || true
          app-store-connect --version || true

      - name: Decode & validate keys (no secrets printed)
        script: |
          set -euo pipefail
          fail(){ echo "❌ $1"; exit 1; }

          # Presence checks
          [ -n "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ]    || fail "APP_STORE_CONNECT_PRIVATE_KEY is empty"
          [ -n "${APP_STORE_CONNECT_KEY_IDENTIFIER:-}" ] || fail "APP_STORE_CONNECT_KEY_IDENTIFIER is empty"
          [ -n "${APP_STORE_CONNECT_ISSUER_ID:-}" ]      || fail "APP_STORE_CONNECT_ISSUER_ID is empty"
          [ -n "${APPLE_TEAM_ID:-}" ]                    || fail "APPLE_TEAM_ID is empty"
          [ -n "${BUNDLE_ID:-}" ]                        || fail "BUNDLE_ID is empty"
          if [ -z "${CERTIFICATE_PRIVATE_KEY_B64:-}" ] && [ -z "${CERTIFICATE_PRIVATE_KEY:-}" ]; then
            fail "Provide CERTIFICATE_PRIVATE_KEY_B64 or CERTIFICATE_PRIVATE_KEY"
          fi

          # Normalize ASC .p8 (PKCS#8)
          printf "%s" "$APP_STORE_CONNECT_PRIVATE_KEY" | tr -d '\r' > /tmp/asc_api_key.p8
          echo "ASC key header: $(head -n1 /tmp/asc_api_key.p8)"
          echo "ASC key footer: $(tail -n1 /tmp/asc_api_key.p8)"
          grep -q "BEGIN PRIVATE KEY" /tmp/asc_api_key.p8 || fail "APP_STORE_CONNECT_PRIVATE_KEY must start with '-----BEGIN PRIVATE KEY-----'"
          grep -q "END PRIVATE KEY"   /tmp/asc_api_key.p8 || fail "APP_STORE_CONNECT_PRIVATE_KEY appears truncated"

          # Decode/normalize certificate private key to /tmp/cert_key_any.pem
          if [ -n "${CERTIFICATE_PRIVATE_KEY_B64:-}" ]; then
            printf "%s" "$CERTIFICATE_PRIVATE_KEY_B64" | tr -d '\r' > /tmp/cert_key.b64
            if base64 --help 2>/dev/null | grep -q -- "--decode"; then DEC="--decode"; else DEC="-D"; fi
            base64 $DEC /tmp/cert_key.b64 > /tmp/cert_key_any.pem || fail "Base64 decode failed for CERTIFICATE_PRIVATE_KEY_B64"
          else
            printf "%s" "$CERTIFICATE_PRIVATE_KEY" | tr -d '\r' > /tmp/cert_key_any.pem
          fi

          echo "Cert key header: $(head -n1 /tmp/cert_key_any.pem)"
          echo "Cert key footer: $(tail -n1 /tmp/cert_key_any.pem)"

          # Ensure PKCS#1 RSA (convert if PKCS#8)
          if grep -q "BEGIN RSA PRIVATE KEY" /tmp/cert_key_any.pem; then
            cp /tmp/cert_key_any.pem /tmp/cert_key.pem
          elif grep -q "BEGIN PRIVATE KEY" /tmp/cert_key_any.pem; then
            openssl pkey -in /tmp/cert_key_any.pem -out /tmp/cert_key.pem >/dev/null 2>&1 || fail "Failed converting PKCS#8 -> PKCS#1"
          else
            fail "CERTIFICATE_PRIVATE_KEY must be 'BEGIN RSA PRIVATE KEY' or 'BEGIN PRIVATE KEY'"
          fi

          # Validate RSA
          openssl rsa -in /tmp/cert_key.pem -check -noout || fail "Invalid RSA key"

          # Re-export normalized values for next steps
          export APP_STORE_CONNECT_PRIVATE_KEY="$(cat /tmp/asc_api_key.p8)"
          export CERTIFICATE_PRIVATE_KEY="$(cat /tmp/cert_key.pem)"
          envman add --key APP_STORE_CONNECT_PRIVATE_KEY --value "$APP_STORE_CONNECT_PRIVATE_KEY"
          envman add --key CERTIFICATE_PRIVATE_KEY --value "$CERTIFICATE_PRIVATE_KEY"

      - name: Install JS deps & sync Capacitor
        script: |
          set -e
          npm ci
          npx cap sync ios

      - name: Provisioning (create/fetch signing files)
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --api-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "$CERTIFICATE_PRIVATE_KEY"
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA (App Store)
        script: |
          set -e
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-method app-store

    artifacts:
      - $CM_BUILD_DIR/IPA/*.ipa
      - $CM_BUILD_DIR/**/Build/**/*.log
      - $CM_BUILD_DIR/ios_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
