workflows:
  ios_capacitor_appstore:
    name: "iOS • Capacitor → App Store"
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials   # MUST contain: APP_STORE_CONNECT_API_KEY or APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_ID or APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID, APPLE_TEAM_ID
      vars:
        BUNDLE_ID: "com.balu.aegispulse"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: 15.4

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install Node deps
        script: |
          npm ci

      - name: Build web assets
        script: |
          npm run build || npm run build:prod || true
          [ -d www ] || mkdir -p www

      - name: Capacitor sync (installs pods)
        script: |
          npx cap sync ios

      - name: Set build number
        script: |
          cd ios/App
          agvtool new-version -all "$BUILD_NUMBER"
          cd -

      # --- Provisioning: fetch/create certs & profiles via App Store Connect API ---
      - name: Provisioning (create/fetch signing files)
        script: |
          set -e

          # Create a temp keychain for this build
          keychain initialize

          echo "Codemagic app-store-connect CLI version:"
          app-store-connect --version || true

          # ---- Normalize variable names expected by different Codemagic/ASC CLI versions ----
          # Accept either KEY_ID or KEY_IDENTIFIER
          if [ -n "${APP_STORE_CONNECT_KEY_ID:-}" ] && [ -z "${APP_STORE_CONNECT_KEY_IDENTIFIER:-}" ]; then
            export APP_STORE_CONNECT_KEY_IDENTIFIER="$APP_STORE_CONNECT_KEY_ID"
          fi

          # Accept either API_KEY or PRIVATE_KEY
          if [ -n "${APP_STORE_CONNECT_API_KEY:-}" ] && [ -z "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ]; then
            export APP_STORE_CONNECT_PRIVATE_KEY="$APP_STORE_CONNECT_API_KEY"
          fi

          # Basic sanity checks
          : "${APP_STORE_CONNECT_ISSUER_ID:?Missing APP_STORE_CONNECT_ISSUER_ID}"
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?Missing APP_STORE_CONNECT_KEY_IDENTIFIER or APP_STORE_CONNECT_KEY_ID}"
          : "${APP_STORE_CONNECT_PRIVATE_KEY:?Missing APP_STORE_CONNECT_PRIVATE_KEY or APP_STORE_CONNECT_API_KEY}"

          # Prepare a private key file (raw or base64)
          ASC_KEY_FILE="$CM_BUILD_DIR/asc_api_key.p8"
          if echo "$APP_STORE_CONNECT_PRIVATE_KEY" | grep -q "BEGIN PRIVATE KEY"; then
            # Raw .p8 text
            printf "%s\n" "$APP_STORE_CONNECT_PRIVATE_KEY" > "$ASC_KEY_FILE"
          else
            # Base64-encoded
            printf "%s" "$APP_STORE_CONNECT_PRIVATE_KEY" | base64 --decode > "$ASC_KEY_FILE"
          fi

          echo "Fetching/creating signing files for bundle id: $BUNDLE_ID"
          # Use explicit auth flags (works across CLI variants)
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key-file "$ASC_KEY_FILE"

          # Install the downloaded certs/profiles into the keychain
          keychain add-certificates

          # Sanity check that Codemagic exported these envs
          echo "Using certificate identity: ${CM_CERTIFICATE_IDENTITY:-<missing>}"
          echo "Using provisioning profile: ${CM_PROVISIONING_PROFILE:-<missing>}"
          if [ -z "$CM_CERTIFICATE_IDENTITY" ] || [ -z "$CM_PROVISIONING_PROFILE" ]; then
            echo "❌ Missing signing assets after fetch. Verify credentials & that the app ($BUNDLE_ID) exists under this team."
            exit 1
          fi

      # --- Archive with MANUAL signing using installed assets ---
      - name: Xcode archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            -destination "generic/platform=iOS" \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="$CM_CERTIFICATE_IDENTITY" \
            PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"

      - name: Export IPA (App Store)
        script: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>stripSwiftSymbols</key><true/>
          </dict></plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/build"

    artifacts:
      - $CM_BUILD_DIR/build/*.ipa
      - $CM_BUILD_DIR/ios_archive.xcarchive

    publishing:
      app_store_connect:
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
