workflows:
  ios_capacitor_manual_signing:
    name: iOS • Capacitor → App Store (manual signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: "com.balu.aegispulse"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APPLE_TEAM_ID: "4ZB476DJS4"
      node: 20
      xcode: 15
    scripts:
      - name: Install deps & sync iOS
        script: |
          set -e
          npm ci
          npx cap sync ios
      - name: Import uploaded certs & profiles
        script: |
          set -euo pipefail
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA (App Store)
        script: |
          set -e
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-method app-store
    artifacts:
      - $CM_BUILD_DIR/IPA/*.ipa
      - $CM_BUILD_DIR/**/Build/**/*.log
      - $CM_BUILD_DIR/ios_logs/*.log
