workflows:
  ios_capacitor_appstore:
    name: "iOS • Capacitor → App Store"
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials   # contains APP_STORE_CONNECT_API_KEY / KEY_ID / ISSUER_ID
      vars:
        BUNDLE_ID: "com.balu.aegispulse"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APPLE_TEAM_ID: "<<<YOUR_TEAM_ID>>>"
      node: 20
      xcode: 15.4

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install Node deps
        script: |
          npm ci

      - name: Build web assets
        script: |
          npm run build || npm run build:prod || true
          # Ensure www exists for Capacitor
          [ -d www ] || mkdir -p www

      - name: Capacitor sync
        script: |
          npx cap sync ios

      - name: Set build number
        script: |
          cd ios/App
          agvtool new-version -all "$BUILD_NUMBER"
          cd -

      - name: Xcode archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            clean archive \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            PROVISIONING_PROFILE_SPECIFIER=""

      - name: Export IPA
        script: |
          cat > exportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>teamID</key><string>${APPLE_TEAM_ID}</string>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/build"

    artifacts:
      - $CM_BUILD_DIR/build/*.ipa
      - $CM_BUILD_DIR/ios_archive.xcarchive

    publishing:
      app_store_connect:
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        api_key: $APP_STORE_CONNECT_API_KEY
        submit_to_testflight: true
        # optionally auto-submit for external testing:
        # submit_to_app_store: false
