workflows:
  ios_capacitor_appstore:
    name: iOS • Capacitor • App Store
    environment:
      groups:
        - appstore_credentials    # create this env group in Codemagic (see below)
      vars:
        BUNDLE_ID: "com.balu.aegispulse"
        IOS_SCHEME: "App"
      node: 20
      xcode: 15.4
    scripts:
      - name: Install Node deps
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build || npm run build:prod || true
          # ensure we have www/
          if [ -d dist ]; then rm -rf www && cp -r dist www; fi
      - name: Ensure Capacitor iOS project exists & sync
        script: |
          # add ios only if not present
          if [ ! -d "ios" ]; then npx cap add ios; fi
          npx cap sync ios
      - name: CocoaPods install
        script: |
          cd ios/App
          pod install --repo-update
      - name: Set bundle id
        script: |
          cd ios/App
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" App/Info.plist || true
    ios:
      xcode_workspace: "ios/App/App.xcworkspace"
      xcode_scheme: "$IOS_SCHEME"
      export_method: "app-store"
      bundle_identifier: "$BUNDLE_ID"
      automatic_code_signing: true
      distribution_type: app_store
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
